"""add recency score

Revision ID: 1aa58f9bdb22
Revises: e79d4c6eeaf2
Create Date: 2026-08-08 19:32:45.215826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aa58f9bdb22'
down_revision: Union[str, Sequence[str], None] = 'e79d4c6eeaf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_interactions', sa.Column('recency_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_interactions', 'recency_score')
    # ### end Alembic commands ###
