"""create behavior profiles

Revision ID: 5e31e5e51957
Revises: 2e9d5494bf59
Create Date: 2026-08-08 15:23:29.537125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e31e5e51957'
down_revision: Union[str, Sequence[str], None] = '2e9d5494bf59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behavior_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_scores', sa.JSON(), nullable=True),
    sa.Column('difficulty_scores', sa.JSON(), nullable=True),
    sa.Column('language_scores', sa.JSON(), nullable=True),
    sa.Column('search_frequency', sa.Integer(), nullable=False),
    sa.Column('average_time_spent', sa.Float(), nullable=False),
    sa.Column('average_scroll_depth', sa.Float(), nullable=False),
    sa.Column('purchase_intent', sa.Float(), nullable=False),
    sa.Column('total_events', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_behavior_profiles_id'), 'behavior_profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_behavior_profiles_id'), table_name='behavior_profiles')
    op.drop_table('behavior_profiles')
    # ### end Alembic commands ###
