"""add final interaction score

Revision ID: 9b44bcf0484f
Revises: 1aa58f9bdb22
Create Date: 2026-08-08 20:03:52.905822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b44bcf0484f'
down_revision: Union[str, Sequence[str], None] = '1aa58f9bdb22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_interactions', sa.Column('final_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_interactions', 'final_score')
    # ### end Alembic commands ###
