"""add product interaction uniqueness

Revision ID: e79d4c6eeaf2
Revises: f2e37f77a7db
Create Date: 2026-08-08 18:08:24.938152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e79d4c6eeaf2'
down_revision: Union[str, Sequence[str], None] = 'f2e37f77a7db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_product_interaction', 'product_interactions', ['user_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_product_interaction', 'product_interactions', type_='unique')
    # ### end Alembic commands ###
