"""create product interactions

Revision ID: f2e37f77a7db
Revises: 5e31e5e51957
Create Date: 2026-08-08 18:01:31.339869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2e37f77a7db'
down_revision: Union[str, Sequence[str], None] = '5e31e5e51957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('total_time_spent', sa.Float(), nullable=False),
    sa.Column('max_scroll_depth', sa.Float(), nullable=False),
    sa.Column('search_count', sa.Integer(), nullable=False),
    sa.Column('interaction_score', sa.Float(), nullable=False),
    sa.Column('last_interacted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_interactions_id'), 'product_interactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_interactions_id'), table_name='product_interactions')
    op.drop_table('product_interactions')
    # ### end Alembic commands ###
